#!/bin/bash
# Part of rtf2latex by Scott Prahl (Mar 2012)
#
# This version uses LibreOffice and jodconverter 
#
#set -x  # uncomment for debugging
#

JODDIR="/Library/Java/Extensions/lib/"
JOD="jodconverter-core-3.0-beta-4.jar"
VERSION="1.0"

help()
{
cat <<HELP
convert2pdf -- convert vector based image formats to PDF

USAGE: convert2pdf file[.wmf|.emf|.pict]

OPTIONS: 
         -h             help
         -v             version

EXAMPLES: 
         convert2pdf file.emf
         convert2pdf file.wmf
         convert2pdf file.pict

HELP
exit 0
}

version()
{
echo "convert2pdf $VERSION"
exit 0
}

while [ -n "$1" ]; do
case $1 in
    -h) help;              shift 1;;
    -v) version;           shift 1;;
    --) break;;
    -*) echo "convert2pdf: error: no such option $1"; exit 1;;
    *)  break;;
esac
done

# is there an input file?
if [ -z "$*" ] ; then
    echo "convert2pdf: error: no input file specified"
    exit 1
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for input in $*
do	
	bname=${input%.*}
	pdfname="$bname.pdf"
	
	if [ ! -f "$input" ] ; then
	 echo "convert2pdf: error: input file '$input' does not exist"
	 exit 1
	fi
	
	java -jar $JODDIR$JOD "$input" "$pdfname" 1> /dev/null 2> /dev/null

done
IFS=$SAVEIFS

exit 0
