#!/bin/bash
# Part of rtf2latex2e by Scott Prahl (June 2012)
#
# This version uses OpenOffice/LibreOffice and jodconverter 
#
#set -x  # uncomment for debugging
#

JODDIR="/Library/Java/Extensions/lib/"
JOD="jodconverter-core-3.0-beta-4.jar"
VERSION="1.0"

help()
{
cat <<HELP
vectorimage2pdf -- convert vector-based image formats to PDF

USAGE: vectorimage2pdf file[.wmf|.emf|.pict]

OPTIONS: 
         -h             help
         -v             version

EXAMPLES: 
         vectorimage2pdf file.emf
         vectorimage2pdf file.wmf
         vectorimage2pdf file.pict

HELP
exit 0
}

version()
{
echo "vectorimage2pdf $VERSION"
exit 0
}

while [ -n "$1" ]; do
case $1 in
    -h) help;              shift 1;;
    -v) version;           shift 1;;
    --) break;;
    -*) echo "vectorimage2pdf: error: no such option $1"; exit 1;;
    *)  break;;
esac
done

# does the jodconvert utility exist
if [ ! -f "$JODDIR$JOD" ] ; then
 echo "vectorimage2pdf: error: jodconverter is missing "
 echo "                        '$JODDIR$JOD' does not exist"
 echo "                        see http://code.google.com/p/jodconverter/"
 exit 1
fi

# is there an input file?
if [ -z "$*" ] ; then
    echo "vectorimage2pdf: error: no input file specified"
    exit 1
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for input in $*
do	
	bname=${input%.*}
	pdfname="$bname.pdf"
	
	if [ ! -f "$input" ] ; then
	 echo "vectorimage2pdf: error: input file '$input' does not exist"
	 exit 1
	fi
	
	java -jar $JODDIR$JOD "$input" "$pdfname" 1> /dev/null 2> /dev/null

done
IFS=$SAVEIFS

exit 0
