/* The following defines are automatically generated from standard-names */
/* They must be sequential beginning from zero */
/* Do not edit. */

#define rtfSC_nothing	0
#define rtfSC_space	1
#define rtfSC_exclam	2
#define rtfSC_quotedbl	3
#define rtfSC_numbersign	4
#define rtfSC_dollar	5
#define rtfSC_percent	6
#define rtfSC_ampersand	7
#define rtfSC_quoteright	8
#define rtfSC_parenleft	9
#define rtfSC_parenright	10
#define rtfSC_asterisk	11
#define rtfSC_plus	12
#define rtfSC_comma	13
#define rtfSC_hyphen	14
#define rtfSC_period	15
#define rtfSC_slash	16
#define rtfSC_zero	17
#define rtfSC_one	18
#define rtfSC_two	19
#define rtfSC_three	20
#define rtfSC_four	21
#define rtfSC_five	22
#define rtfSC_six	23
#define rtfSC_seven	24
#define rtfSC_eight	25
#define rtfSC_nine	26
#define rtfSC_colon	27
#define rtfSC_semicolon	28
#define rtfSC_less	29
#define rtfSC_equal	30
#define rtfSC_greater	31
#define rtfSC_question	32
#define rtfSC_at	33
#define rtfSC_A	34
#define rtfSC_B	35
#define rtfSC_C	36
#define rtfSC_D	37
#define rtfSC_E	38
#define rtfSC_F	39
#define rtfSC_G	40
#define rtfSC_H	41
#define rtfSC_I	42
#define rtfSC_J	43
#define rtfSC_K	44
#define rtfSC_L	45
#define rtfSC_M	46
#define rtfSC_N	47
#define rtfSC_O	48
#define rtfSC_P	49
#define rtfSC_Q	50
#define rtfSC_R	51
#define rtfSC_S	52
#define rtfSC_T	53
#define rtfSC_U	54
#define rtfSC_V	55
#define rtfSC_W	56
#define rtfSC_X	57
#define rtfSC_Y	58
#define rtfSC_Z	59
#define rtfSC_bracketleft	60
#define rtfSC_backslash	61
#define rtfSC_bracketright	62
#define rtfSC_asciicircum	63
#define rtfSC_underscore	64
#define rtfSC_quoteleft	65
#define rtfSC_a	66
#define rtfSC_b	67
#define rtfSC_c	68
#define rtfSC_d	69
#define rtfSC_e	70
#define rtfSC_f	71
#define rtfSC_g	72
#define rtfSC_h	73
#define rtfSC_i	74
#define rtfSC_j	75
#define rtfSC_k	76
#define rtfSC_l	77
#define rtfSC_m	78
#define rtfSC_n	79
#define rtfSC_o	80
#define rtfSC_p	81
#define rtfSC_q	82
#define rtfSC_r	83
#define rtfSC_s	84
#define rtfSC_t	85
#define rtfSC_u	86
#define rtfSC_v	87
#define rtfSC_w	88
#define rtfSC_x	89
#define rtfSC_y	90
#define rtfSC_z	91
#define rtfSC_braceleft	92
#define rtfSC_bar	93
#define rtfSC_braceright	94
#define rtfSC_asciitilde	95
#define rtfSC_exclamdown	96
#define rtfSC_cent	97
#define rtfSC_sterling	98
#define rtfSC_fraction	99
#define rtfSC_yen	100
#define rtfSC_section	101
#define rtfSC_quotedblleft	102
#define rtfSC_guillemotleft	103
#define rtfSC_guilsinglleft	104
#define rtfSC_guilsinglright	105
#define rtfSC_fi	106
#define rtfSC_fl	107
#define rtfSC_endash	108
#define rtfSC_dagger	109
#define rtfSC_daggerdbl	110
#define rtfSC_periodcentered	111
#define rtfSC_paragraph	112
#define rtfSC_bullet	113
#define rtfSC_quotesinglbase	114
#define rtfSC_quotedblbase	115
#define rtfSC_quotedblright	116
#define rtfSC_guillemotright	117
#define rtfSC_ellipsis	118
#define rtfSC_perthousand	119
#define rtfSC_questiondown	120
#define rtfSC_grave	121
#define rtfSC_acute	122
#define rtfSC_circumflex	123
#define rtfSC_tilde	124
#define rtfSC_macron	125
#define rtfSC_breve	126
#define rtfSC_dotaccent	127
#define rtfSC_diaeresis	128
#define rtfSC_ring	129
#define rtfSC_cedilla	130
#define rtfSC_hungarumlaut	131
#define rtfSC_ogonek	132
#define rtfSC_caron	133
#define rtfSC_emdash	134
#define rtfSC_AE	135
#define rtfSC_ordfeminine	136
#define rtfSC_Lslash	137
#define rtfSC_Oslash	138
#define rtfSC_OE	139
#define rtfSC_ordmasculine	140
#define rtfSC_ae	141
#define rtfSC_dotlessi	142
#define rtfSC_lslash	143
#define rtfSC_oslash	144
#define rtfSC_oe	145
#define rtfSC_germandbls	146
#define rtfSC_Aacute	147
#define rtfSC_Acircumflex	148
#define rtfSC_Adiaeresis	149
#define rtfSC_Agrave	150
#define rtfSC_Aring	151
#define rtfSC_Atilde	152
#define rtfSC_Ccedilla	153
#define rtfSC_Eacute	154
#define rtfSC_Ecircumflex	155
#define rtfSC_Ediaeresis	156
#define rtfSC_Egrave	157
#define rtfSC_Eth	158
#define rtfSC_Iacute	159
#define rtfSC_Icircumflex	160
#define rtfSC_Idiaeresis	161
#define rtfSC_Igrave	162
#define rtfSC_Ntilde	163
#define rtfSC_Oacute	164
#define rtfSC_Ocircumflex	165
#define rtfSC_Odiaeresis	166
#define rtfSC_Ograve	167
#define rtfSC_Otilde	168
#define rtfSC_Scaron	169
#define rtfSC_Thorn	170
#define rtfSC_Uacute	171
#define rtfSC_Ucircumflex	172
#define rtfSC_Udiaeresis	173
#define rtfSC_Ugrave	174
#define rtfSC_Yacute	175
#define rtfSC_Ydiaeresis	176
#define rtfSC_aacute	177
#define rtfSC_acircumflex	178
#define rtfSC_adiaeresis	179
#define rtfSC_agrave	180
#define rtfSC_aring	181
#define rtfSC_atilde	182
#define rtfSC_brokenbar	183
#define rtfSC_ccedilla	184
#define rtfSC_copyright	185
#define rtfSC_degree	186
#define rtfSC_divide	187
#define rtfSC_eacute	188
#define rtfSC_ecircumflex	189
#define rtfSC_ediaeresis	190
#define rtfSC_egrave	191
#define rtfSC_iacute	192
#define rtfSC_icircumflex	193
#define rtfSC_idiaeresis	194
#define rtfSC_igrave	195
#define rtfSC_logicalnot	196
#define rtfSC_minus	197
#define rtfSC_multiply	198
#define rtfSC_ntilde	199
#define rtfSC_oacute	200
#define rtfSC_ocircumflex	201
#define rtfSC_odiaeresis	202
#define rtfSC_ograve	203
#define rtfSC_onesuperior	204
#define rtfSC_otilde	205
#define rtfSC_plusminus	206
#define rtfSC_registered	207
#define rtfSC_scaron	208
#define rtfSC_th	209
#define rtfSC_thorn	210
#define rtfSC_threesuperior	211
#define rtfSC_trademark	212
#define rtfSC_twosuperior	213
#define rtfSC_uacute	214
#define rtfSC_ucircumflex	215
#define rtfSC_udiaeresis	216
#define rtfSC_ugrave	217
#define rtfSC_yacute	218
#define rtfSC_ydiaeresis	219
#define rtfSC_Alpha	220
#define rtfSC_Beta	221
#define rtfSC_Chi	222
#define rtfSC_Delta	223
#define rtfSC_Epsilon	224
#define rtfSC_Phi	225
#define rtfSC_Gamma	226
#define rtfSC_Eta	227
#define rtfSC_Iota	228
#define rtfSC_Kappa	229
#define rtfSC_Lambda	230
#define rtfSC_Mu	231
#define rtfSC_Nu	232
#define rtfSC_Omicron	233
#define rtfSC_Pi	234
#define rtfSC_Theta	235
#define rtfSC_Rho	236
#define rtfSC_Sigma	237
#define rtfSC_Tau	238
#define rtfSC_Upsilon	239
#define rtfSC_varUpsilon	240
#define rtfSC_Omega	241
#define rtfSC_Xi	242
#define rtfSC_Psi	243
#define rtfSC_Zeta	244
#define rtfSC_alpha	245
#define rtfSC_beta	246
#define rtfSC_chi	247
#define rtfSC_delta	248
#define rtfSC_epsilon	249
#define rtfSC_varepsilon	250
#define rtfSC_phi	251
#define rtfSC_varphi	252
#define rtfSC_gamma	253
#define rtfSC_eta	254
#define rtfSC_iota	255
#define rtfSC_kappa	256
#define rtfSC_lambda	257
#define rtfSC_mu	258
#define rtfSC_nu	259
#define rtfSC_omicron	260
#define rtfSC_pi	261
#define rtfSC_varpi	262
#define rtfSC_theta	263
#define rtfSC_vartheta	264
#define rtfSC_rho	265
#define rtfSC_varrho	266
#define rtfSC_sigma	267
#define rtfSC_varsigma	268
#define rtfSC_tau	269
#define rtfSC_upsilon	270
#define rtfSC_omega	271
#define rtfSC_xi	272
#define rtfSC_psi	273
#define rtfSC_zeta	274
#define rtfSC_nobrkspace	275
#define rtfSC_nobrkhyphen	276
#define rtfSC_lessequal	277
#define rtfSC_greaterequal	278
#define rtfSC_infinity	279
#define rtfSC_integral	280
#define rtfSC_notequal	281
#define rtfSC_radical	282
#define rtfSC_radicalex	283
#define rtfSC_approxequal	284
#define rtfSC_apple	285
#define rtfSC_partialdiff	286
#define rtfSC_opthyphen	287
#define rtfSC_formula	288
#define rtfSC_universal	289
#define rtfSC_existential	290
#define rtfSC_suchthat	291
#define rtfSC_congruent	292
#define rtfSC_perpendicular	293
#define rtfSC_minute	294
#define rtfSC_club	295
#define rtfSC_diamond	296
#define rtfSC_heart	297
#define rtfSC_spade	298
#define rtfSC_arrowboth	299
#define rtfSC_arrowleft	300
#define rtfSC_arrowup	301
#define rtfSC_arrowright	302
#define rtfSC_arrowdown	303
#define rtfSC_second	304
#define rtfSC_proportional	305
#define rtfSC_equivalence	306
#define rtfSC_arrowvertex	307
#define rtfSC_arrowhorizex	308
#define rtfSC_carriagereturn	309
#define rtfSC_aleph	310
#define rtfSC_weierstrass	311
#define rtfSC_circlemultiply	312
#define rtfSC_circleplus	313
#define rtfSC_emptyset	314
#define rtfSC_intersection	315
#define rtfSC_union	316
#define rtfSC_propersuperset	317
#define rtfSC_reflexsuperset	318
#define rtfSC_notsubset	319
#define rtfSC_propersubset	320
#define rtfSC_reflexsubset	321
#define rtfSC_element	322
#define rtfSC_notelement	323
#define rtfSC_angle	324
#define rtfSC_gradient	325
#define rtfSC_product	326
#define rtfSC_logicaland	327
#define rtfSC_logicalor	328
#define rtfSC_arrowdblboth	329
#define rtfSC_arrowdblleft	330
#define rtfSC_arrowdblup	331
#define rtfSC_arrowdblright	332
#define rtfSC_arrowdbldown	333
#define rtfSC_angleleft	334
#define rtfSC_registersans	335
#define rtfSC_copyrightsans	336
#define rtfSC_trademarksans	337
#define rtfSC_angleright	338
#define rtfSC_mathplus	339
#define rtfSC_mathminus	340
#define rtfSC_mathasterisk	341
#define rtfSC_mathnumbersign	342
#define rtfSC_dotmath	343
#define rtfSC_mathequal	344
#define rtfSC_mathtilde	345
#define rtfSC_newline	346
#define rtfSC_bracevert	347
#define rtfSC_Cdblhorizbar	348
#define rtfSC_forall	349
#define rtfSC_jmath	350
#define rtfSC_langle	351
#define rtfSC_lceil	352
#define rtfSC_lfloor	353
#define rtfSC_midbar	354
#define rtfSC_nabla	355
#define rtfSC_powern	356
#define rtfSC_powerone	357
#define rtfSC_powertwo	358
#define rtfSC_powerthree	359
#define rtfSC_rangle	360
#define rtfSC_rceil	361
#define rtfSC_rfloor	362
#define rtfSC_subset	363
#define rtfSC_subseteq	364
#define rtfSC_sum	365
#define rtfSC_supset	366
#define rtfSC_supseteq	367
#define rtfSC_therefore	368
#define rtfSC_lozenge	369
#define rtfSC_diagup	370
#define rtfSC_mho	371
#define rtfSC_eth	372
#define rtfSC_Ifraktur	373
#define rtfSC_Rfraktur	374
#define rtfSC_currency	375
#define rtfSC_florin	376
#define rtfSC_onehalf	377
#define rtfSC_onequarter	378
#define rtfSC_threequarters	379
#define rtfSC_Abreve	380
#define rtfSC_Aogonek	381
#define rtfSC_abreve	382
#define rtfSC_acutedbl	383
#define rtfSC_aogonek	384
#define rtfSC_Cacute	385
#define rtfSC_Ccaron	386
#define rtfSC_cacute	387
#define rtfSC_ccaron	388
#define rtfSC_Dcaron	389
#define rtfSC_Dslash	390
#define rtfSC_dcaron	391
#define rtfSC_dslash	392
#define rtfSC_Ecaron	393
#define rtfSC_Eogonek	394
#define rtfSC_ecaron	395
#define rtfSC_eogonek	396
#define rtfSC_Lacute	397
#define rtfSC_Lcaron	398
#define rtfSC_lacute	399
#define rtfSC_lcaron	400
#define rtfSC_Nacute	401
#define rtfSC_Ncaron	402
#define rtfSC_nacute	403
#define rtfSC_ncaron	404
#define rtfSC_Oacutedbl	405
#define rtfSC_oacutedbl	406
#define rtfSC_Racute	407
#define rtfSC_Rcaron	408
#define rtfSC_racute	409
#define rtfSC_rcaron	410
#define rtfSC_Sacute	411
#define rtfSC_Scedilla	412
#define rtfSC_sacute	413
#define rtfSC_scedilla	414
#define rtfSC_Tcaron	415
#define rtfSC_Tcedilla	416
#define rtfSC_tcaron	417
#define rtfSC_tcedilla	418
#define rtfSC_Uacutedbl	419
#define rtfSC_Uring	420
#define rtfSC_uacutedbl	421
#define rtfSC_uring	422
#define rtfSC_Zacute	423
#define rtfSC_Zcaron	424
#define rtfSC_Zdotaccent	425
#define rtfSC_zacute	426
#define rtfSC_zcaron	427
#define rtfSC_zdotaccent	428
#define rtfSC_Gbreve	429
#define rtfSC_gbreve	430
#define rtfSC_Idotaccent	431
#define rtfSC_euro	432
#define rtfSC_CYRILLIC_CAPITAL_LETTER_DJE	433
#define rtfSC_CYRILLIC_CAPITAL_LETTER_GJE	434
#define rtfSC_CYRILLIC_SMALL_LETTER_GJE	435
#define rtfSC_CYRILLIC_CAPITAL_LETTER_LJE	436
#define rtfSC_CYRILLIC_CAPITAL_LETTER_NJE	437
#define rtfSC_CYRILLIC_CAPITAL_LETTER_KJE	438
#define rtfSC_CYRILLIC_CAPITAL_LETTER_TSHE	439
#define rtfSC_CYRILLIC_CAPITAL_LETTER_DZHE	440
#define rtfSC_CYRILLIC_SMALL_LETTER_DJE	441
#define rtfSC_CYRILLIC_SMALL_LETTER_LJE	442
#define rtfSC_CYRILLIC_SMALL_LETTER_NJE	443
#define rtfSC_CYRILLIC_SMALL_LETTER_KJE	444
#define rtfSC_CYRILLIC_SMALL_LETTER_TSHE	445
#define rtfSC_CYRILLIC_SMALL_LETTER_DZHE	446
#define rtfSC_CYRILLIC_CAPITAL_LETTER_SHORT_U	447
#define rtfSC_CYRILLIC_SMALL_LETTER_SHORT_U	448
#define rtfSC_CYRILLIC_CAPITAL_LETTER_JE	449
#define rtfSC_CYRILLIC_CAPITAL_LETTER_GHE_WITH_UPTURN	450
#define rtfSC_CYRILLIC_CAPITAL_LETTER_IO	451
#define rtfSC_CYRILLIC_CAPITAL_LETTER_UKRAINIAN_IE	452
#define rtfSC_CYRILLIC_CAPITAL_LETTER_YI	453
#define rtfSC_CYRILLIC_CAPITAL_LETTER_BYELORUSSIAN_UKRAINIAN_I	454
#define rtfSC_CYRILLIC_SMALL_LETTER_BYELORUSSIAN_UKRAINIAN_I	455
#define rtfSC_CYRILLIC_SMALL_LETTER_GHE_WITH_UPTURN	456
#define rtfSC_CYRILLIC_SMALL_LETTER_IO	457
#define rtfSC_CYRILLIC_SMALL_LETTER_UKRAINIAN_IE	458
#define rtfSC_CYRILLIC_SMALL_LETTER_JE	459
#define rtfSC_CYRILLIC_CAPITAL_LETTER_DZE	460
#define rtfSC_CYRILLIC_SMALL_LETTER_DZE	461
#define rtfSC_CYRILLIC_SMALL_LETTER_YI	462
#define rtfSC_CYRILLIC_CAPITAL_LETTER_A	463
#define rtfSC_CYRILLIC_CAPITAL_LETTER_BE	464
#define rtfSC_CYRILLIC_CAPITAL_LETTER_VE	465
#define rtfSC_CYRILLIC_CAPITAL_LETTER_GHE	466
#define rtfSC_CYRILLIC_CAPITAL_LETTER_DE	467
#define rtfSC_CYRILLIC_CAPITAL_LETTER_IE	468
#define rtfSC_CYRILLIC_CAPITAL_LETTER_ZHE	469
#define rtfSC_CYRILLIC_CAPITAL_LETTER_ZE	470
#define rtfSC_CYRILLIC_CAPITAL_LETTER_I	471
#define rtfSC_CYRILLIC_CAPITAL_LETTER_SHORT_I	472
#define rtfSC_CYRILLIC_CAPITAL_LETTER_KA	473
#define rtfSC_CYRILLIC_CAPITAL_LETTER_EL	474
#define rtfSC_CYRILLIC_CAPITAL_LETTER_EM	475
#define rtfSC_CYRILLIC_CAPITAL_LETTER_EN	476
#define rtfSC_CYRILLIC_CAPITAL_LETTER_O	477
#define rtfSC_CYRILLIC_CAPITAL_LETTER_PE	478
#define rtfSC_CYRILLIC_CAPITAL_LETTER_ER	479
#define rtfSC_CYRILLIC_CAPITAL_LETTER_ES	480
#define rtfSC_CYRILLIC_CAPITAL_LETTER_TE	481
#define rtfSC_CYRILLIC_CAPITAL_LETTER_U	482
#define rtfSC_CYRILLIC_CAPITAL_LETTER_EF	483
#define rtfSC_CYRILLIC_CAPITAL_LETTER_HA	484
#define rtfSC_CYRILLIC_CAPITAL_LETTER_TSE	485
#define rtfSC_CYRILLIC_CAPITAL_LETTER_CHE	486
#define rtfSC_CYRILLIC_CAPITAL_LETTER_SHA	487
#define rtfSC_CYRILLIC_CAPITAL_LETTER_SHCHA	488
#define rtfSC_CYRILLIC_CAPITAL_LETTER_HARD_SIGN	489
#define rtfSC_CYRILLIC_CAPITAL_LETTER_YERU	490
#define rtfSC_CYRILLIC_CAPITAL_LETTER_SOFT_SIGN	491
#define rtfSC_CYRILLIC_CAPITAL_LETTER_E	492
#define rtfSC_CYRILLIC_CAPITAL_LETTER_YU	493
#define rtfSC_CYRILLIC_CAPITAL_LETTER_YA	494
#define rtfSC_CYRILLIC_SMALL_LETTER_A	495
#define rtfSC_CYRILLIC_SMALL_LETTER_BE	496
#define rtfSC_CYRILLIC_SMALL_LETTER_VE	497
#define rtfSC_CYRILLIC_SMALL_LETTER_GHE	498
#define rtfSC_CYRILLIC_SMALL_LETTER_DE	499
#define rtfSC_CYRILLIC_SMALL_LETTER_IE	500
#define rtfSC_CYRILLIC_SMALL_LETTER_ZHE	501
#define rtfSC_CYRILLIC_SMALL_LETTER_ZE	502
#define rtfSC_CYRILLIC_SMALL_LETTER_I	503
#define rtfSC_CYRILLIC_SMALL_LETTER_SHORT_I	504
#define rtfSC_CYRILLIC_SMALL_LETTER_KA	505
#define rtfSC_CYRILLIC_SMALL_LETTER_EL	506
#define rtfSC_CYRILLIC_SMALL_LETTER_EM	507
#define rtfSC_CYRILLIC_SMALL_LETTER_EN	508
#define rtfSC_CYRILLIC_SMALL_LETTER_O	509
#define rtfSC_CYRILLIC_SMALL_LETTER_PE	510
#define rtfSC_CYRILLIC_SMALL_LETTER_ER	511
#define rtfSC_CYRILLIC_SMALL_LETTER_ES	512
#define rtfSC_CYRILLIC_SMALL_LETTER_TE	513
#define rtfSC_CYRILLIC_SMALL_LETTER_U	514
#define rtfSC_CYRILLIC_SMALL_LETTER_EF	515
#define rtfSC_CYRILLIC_SMALL_LETTER_HA	516
#define rtfSC_CYRILLIC_SMALL_LETTER_TSE	517
#define rtfSC_CYRILLIC_SMALL_LETTER_CHE	518
#define rtfSC_CYRILLIC_SMALL_LETTER_SHA	519
#define rtfSC_CYRILLIC_SMALL_LETTER_SHCHA	520
#define rtfSC_CYRILLIC_SMALL_LETTER_HARD_SIGN	521
#define rtfSC_CYRILLIC_SMALL_LETTER_YERU	522
#define rtfSC_CYRILLIC_SMALL_LETTER_SOFT_SIGN	523
#define rtfSC_CYRILLIC_SMALL_LETTER_E	524
#define rtfSC_CYRILLIC_SMALL_LETTER_YU	525
#define rtfSC_CYRILLIC_SMALL_LETTER_YA	526

#define rtfSC_MaxChar	527
